name: Hello World Workflow

on: [push]

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World Message
        run: echo "Hello World"
      - name: Print a goodbye message
        run: echo "Goodbye, World"
